### ISSUE TITLE
Client application does not remove session on Devise::CasSessionsController#single_sign_out

### ISSUE THREAD

**Issue by Dimcha** [nbudin/devise_cas_authenticatable#125]
In Gemfile:
```
gem 'devise'
gem 'devise_cas_authenticatable'
gem 'activerecord-session_store'
```
In session_store.rb:
```
Rails.application.config.session_store :active_record_store, :key => '_my_application_session'
```
In devise.rb:
```
  config.cas_base_url = "http://localhost:3001/"
  config.cas_enable_single_sign_out = true
  config.cas_username_column = "email"
```

If I press SignOut on my application it removes session on both and my application and server.
If I press SignOut on server my application gets request:
```
Started POST "/users/service" for 127.0.0.1 at 2016-06-08 13:07:03 +0300
Processing by Devise::CasSessionsController#single_sign_out as */*
  Parameters: {"logoutRequest"=>"<samlp:LogoutRequest xmlns:samlp=\"urn:oasis:names:tc:SAML:2.0:protocol\" xmlns:saml=\"urn:oasis:names:tc:SAML:2.0:assertion\" ID=\"a0ca981e-3aab-413f-9b4b-c9a18a7381fd\" Version=\"2.0\" IssueInstant=\"2016-06-08 13:07:03 +0300\">\n  <saml:NameID>@NOT_USED@</saml:NameID>\n  <samlp:SessionIndex>ST-14653804225956-I5KGnnMUpQeLYvdcSWtw5xoRdQHvLamSGt7BBXLv</samlp:SessionIndex>\n</samlp:LogoutRequest>\n"}
Redirected to http://localhost:3001/login?service=http%3A%2F%2Flocalhost%3A3000%2Fusers%2Fservice
Filter chain halted as :redirect_to_sign_in rendered or redirected
Completed 302 Found in 5ms (ActiveRecord: 0.0ms)
```
and the session in my application is not removed. Any ideas why is it so?
Also as you can see I did not get any notification from single_sign_out method, what is also weird.

**Comment by nbudin** [comment]
Hi @Dimcha!  Based on your server log it seems as if your CasSessionsController is requiring authentication for the single_sign_out action, which it doesn't do by default.  I can think of two possibilities:

1. You've created a custom subclass of CasSessionsController (which I don't think you did, because you didn't mention it).  If that's the case, please make sure it's not requiring authentication for that action accidentally.
2. You've put an over-broad before_action filter in your ApplicationController which is requiring authentication by default.  If that's the case, you will need to make an exception in this filter for the CasSessionsController#single_sign_out action, or alternatively make a custom subclass of CasSessionsController (see the README for instructions on how) and skip the before_filter in there.

**Comment by Dimcha** [comment]
Thank you @nbudin  :) 
It was the before_action.
