### ISSUE TITLE
Changing service URL to https

### ISSUE THREAD

**Issue by beyto1974** [nbudin/devise_cas_authenticatable#135]
Hi,
I would like to forward to http in place of https.

Say:
  https://cas.server.org/login?service=http%3A%2F%2Fmycasapp.org%2Fusers%2Fservice
To:
  https://cas.server.org/login?service=https%3A%2F%2Fwww.mycasapp.org%2Fusers%2Fservice

I don't see any option to configure this.

Thanks,

**Comment by nbudin** [comment]
The service URL is determined using the Rails route helpers in your app.  So the configuration for it is (typically) in your environment initializers, using `config.action_mailer.default_url_options`.

According to [Rails 5 docs](http://api.rubyonrails.org/classes/ActionMailer/Base.html), if you've set the `config.force_ssl` option to true it will generate https URLs by default, so that is probably worth a shot.
