### ISSUE TITLE
After succesful login, nothing happens

### ISSUE THREAD

**Issue by k-godfrey22** [nbudin/devise_cas_authenticatable#144]
Hi there. Once I successfully login to my CAS server, nothing happens. Isnt the "config.cas_destination_url" param where I define where I want to land after a successful login?

**Comment by k-godfrey22** [comment]
When I run my app, I click login and it goes to my CAS server, which is through Texas A&M University, then I successfully login and it just remians on the "Successfully logged in page" on the CAS server. After successful login I want it to continue to a page in my app. I've tried different things. Not sure what I am doing wrong

**Comment by nbudin** [comment]
OK, so here's what Texas A&M's IT department says about the CAS flow: http://infrastructure.tamu.edu/auth/CAS/cas.html#tab_tab2

In particular, they say they'll redirect back to your server in step 5.  That doesn't seem to be happening.  Back in step 1, your app is supposed to have redirected the user to their CAS server with a `service=` parameter in the query string of the URL.  Check to make sure that, in fact, it generated that URL properly.  It should start with `http://localhost`, probably.

If the `service` parameter does look OK to you, I would encourage you to bring this issue to the TAMU IT department, since it seems their CAS server isn't redirecting back to your app.

**Comment by k-godfrey22** [comment]
Okay thank you! I will try that.

**Comment by nbudin** [comment]
OK, cool - I'm going to close this issue for now.  If you do discover the `service` parameter isn't being generated correctly, feel free to reopen it, since that would indicate a possible bug in device_cas_authenticatable.
