### ISSUE TITLE
Disable SingleSignOut on selected API routes

### ISSUE THREAD

**Issue by karticodes** [nbudin/devise_cas_authenticatable#157]
I am working on a RoR app which uses this gem. The app contains both the web app and APIs. Whenever the API is called, it also performs `DeviseCasAuthenticatable::SingleSignOut::StoreSessionId#call` which is not desirable.
Though it is not creating any major issues, it is slightly increasing the API latency.

Is there way to disable this?

**Comment by nbudin** [comment]
Hi @karticodes, if you want you can try upgrading to the pre-release `2.0.0.alpha1` version of this gem.  It significantly reduces the complexity of the gem and removes the `DeviseCasAuthenticatable::SingleSignOut` module entirely (because rack-cas now handles single sign-out for us).  It should improve your performance a bit.

**Comment by nbudin** [comment]
Now that version 2.0.0 is out, this should no longer be an issue.  Closing; if it still is a problem with 2.0.0 please let me know!
