### ISSUE TITLE
Flash alert being set for successful login

### ISSUE THREAD

**Issue by alextakitani** [nbudin/devise_cas_authenticatable#81]
After a user is authenticated on cas, the flash alert is being filled with failure.inauthenticated.

I'm using rails 4 + jasig cas. How can I debug this? Tks!

**Comment by luckyruby** [comment]
How do you handle the scenario of unregistered users where the user exists in CAS but not in your app. I'm getting a redirect loop due to user_signed_in? returning false for this scenario.

**Comment by nbudin** [comment]
@luckyruby: for such situations, I recommend setting the `Devise.cas_create_user` configuration setting, as detailed in the README file.

**Comment by luckyruby** [comment]
@nbudin I have ```Devise.cas_create_user``` set to false already but the issue is that ```before_action :redirect_to_sign_in, unless: :user_signed_in?``` gets called before https://github.com/nbudin/devise_cas_authenticatable/blob/master/app/views/devise/cas_sessions/unregistered.html.erb gets rendered, resulting in a redirect loop.

**Comment by nbudin** [comment]
@luckyruby: sorry, I'm a little confused.  Could you clarify:

1. From what I understand, you are hoping to make it so that users who exist in the CAS server but not in your app's database will *not* automatically be added to your app's database.  Is that correct?
2. I'm not sure where the line you're referring to (`before_action :redirect_to_sign_in, unless: :user_signed_in?`) is located; it is not in `CasSessionsController`.  I'm probably just missing something.  Could you point me to where it is?

For what it's worth, the way this flow is supposed to work is that eventually, we get to https://github.com/nbudin/devise_cas_authenticatable/blob/master/lib/devise_cas_authenticatable/strategy.rb#L29 and then Warden redirects the user to the unregistered page.  This should happen because `#authenticate_with_cas_ticket` will return nil (because `cas_create_user` is set to false, so it doesn't create it).  My guess is that something is making the `cas_authenticatable` strategy not reach that line, and therefore not redirect.

**Comment by luckyruby** [comment]
1. Yes, that's correct.
2. It's not in the code base but from your suggestion [above] (https://github.com/nbudin/devise_cas_authenticatable/issues/81#issuecomment-34687237).

Is there a method I can use instead of ```user_signed_in?``` that will return true if the cas ticket is valid even though the user doesn't exist locally. That way, the flow will reach the unregistered logic instead of hitting the redirect loop.

**Comment by nbudin** [comment]
Oh, I see.  Sorry for my confusion; it's been awhile since this ticket.

Here is something totally, 100% ugly that might nonetheless work:

```ruby
before_filter :redirect_to_sign_in, unless: :already_signed_in_or_valid_ticket?

private
def already_signed_in_or_valid_ticket?
  user_signed_in? || valid_ticket?
end

def valid_ticket?
  Devise::Strategies::CasAuthenticatable.new(env).send(:read_ticket, params).try(:is_valid?)
end
```

To make this less ugly, it might be worthwhile to move the `read_ticket` method out of the strategy instance and somewhere more globally accessible - perhaps making it a public class method of the strategy would be appropriate.  I'd welcome a pull request if you're able to get this working.
